var universitas=[
    {
        "id_ova": "1",
        "wrld_rank": "1",
        "nama_univ": "University of Oxford",
        "lokasi": "United Kingdom",
        "score_ova": "96.4",
        "teaching": "92.3",
        "rank_teaching": "5",
        "research": "99.7",
        "rank_rsc": "1",
        "citation": "99",
        "rank_ctn": "28",
        "income": "74.9",
        "rank_inc": "158",
        "int_outlook": "96.2",
        "rank_int_outlook": "28"
    },
    {
        "id_ova": "2",
        "wrld_rank": "2",
        "nama_univ": "Harvard University",
        "lokasi": "United States",
        "score_ova": "95.2",
        "teaching": "94.8",
        "rank_teaching": "1",
        "research": "99",
        "rank_rsc": "3",
        "citation": "99.3",
        "rank_ctn": "20",
        "income": "49.5",
        "rank_inc": "418",
        "int_outlook": "80.5",
        "rank_int_outlook": "214"
    },
    {
        "id_ova": "3",
        "wrld_rank": "3",
        "nama_univ": "University of Cambridge",
        "lokasi": "United Kingdom",
        "score_ova": "94.8",
        "teaching": "90.9",
        "rank_teaching": "7",
        "research": "99.5",
        "rank_rsc": "2",
        "citation": "97",
        "rank_ctn": "61",
        "income": "54.2",
        "rank_inc": "335",
        "int_outlook": "95.8",
        "rank_int_outlook": "34"
    },
    {
        "id_ova": "4",
        "wrld_rank": "3",
        "nama_univ": "Stanford University",
        "lokasi": "United States",
        "score_ova": "94.8",
        "teaching": "94.2",
        "rank_teaching": "2",
        "research": "96.7",
        "rank_rsc": "7",
        "citation": "99.8",
        "rank_ctn": "16",
        "income": "65",
        "rank_inc": "232",
        "int_outlook": "79.8",
        "rank_int_outlook": "223"
    },
    {
        "id_ova": "5",
        "wrld_rank": "5",
        "nama_univ": "Massachusetts Institute of Technology",
        "lokasi": "United States",
        "score_ova": "94.2",
        "teaching": "90.7",
        "rank_teaching": "8",
        "research": "93.6",
        "rank_rsc": "11",
        "citation": "99.8",
        "rank_ctn": "15",
        "income": "90.9",
        "rank_inc": "62",
        "int_outlook": "89.3",
        "rank_int_outlook": "119"
    },
    {
        "id_ova": "6",
        "wrld_rank": "6",
        "nama_univ": "California Institute of Technology",
        "lokasi": "United States",
        "score_ova": "94.1",
        "teaching": "90.9",
        "rank_teaching": "6",
        "research": "97",
        "rank_rsc": "5",
        "citation": "97.3",
        "rank_ctn": "55",
        "income": "89.8",
        "rank_inc": "69",
        "int_outlook": "83.6",
        "rank_int_outlook": "176"
    },
    {
        "id_ova": "7",
        "wrld_rank": "7",
        "nama_univ": "Princeton University",
        "lokasi": "United States",
        "score_ova": "92.4",
        "teaching": "87.6",
        "rank_teaching": "12",
        "research": "95.9",
        "rank_rsc": "8",
        "citation": "99.1",
        "rank_ctn": "25",
        "income": "66",
        "rank_inc": "221",
        "int_outlook": "80.3",
        "rank_int_outlook": "215"
    },
    {
        "id_ova": "8",
        "wrld_rank": "8",
        "nama_univ": "University of California, Berkeley",
        "lokasi": "United States",
        "score_ova": "92.1",
        "teaching": "86.4",
        "rank_teaching": "14",
        "research": "95.8",
        "rank_rsc": "9",
        "citation": "99",
        "rank_ctn": "27",
        "income": "76.8",
        "rank_inc": "145",
        "int_outlook": "78.4",
        "rank_int_outlook": "238"
    },
    {
        "id_ova": "9",
        "wrld_rank": "9",
        "nama_univ": "Yale University",
        "lokasi": "United States",
        "score_ova": "91.4",
        "teaching": "92.6",
        "rank_teaching": "3",
        "research": "92.7",
        "rank_rsc": "14",
        "citation": "97",
        "rank_ctn": "66",
        "income": "55",
        "rank_inc": "323",
        "int_outlook": "70.9",
        "rank_int_outlook": "335"
    },
    {
        "id_ova": "10",
        "wrld_rank": "10",
        "nama_univ": "Imperial College London",
        "lokasi": "United Kingdom",
        "score_ova": "90.4",
        "teaching": "82.8",
        "rank_teaching": "16",
        "research": "90.8",
        "rank_rsc": "17",
        "citation": "98.3",
        "rank_ctn": "40",
        "income": "59.8",
        "rank_inc": "274",
        "int_outlook": "97.5",
        "rank_int_outlook": "17"
    },
    {
        "id_ova": "11",
        "wrld_rank": "11",
        "nama_univ": "Columbia University",
        "lokasi": "United States",
        "score_ova": "89.4",
        "teaching": "89.4",
        "rank_teaching": "10",
        "research": "87.7",
        "rank_rsc": "21",
        "citation": "97.1",
        "rank_ctn": "57",
        "income": "44.8",
        "rank_inc": "569",
        "int_outlook": "79.9",
        "rank_int_outlook": "219"
    },
    {
        "id_ova": "12",
        "wrld_rank": "11",
        "nama_univ": "ETH Zurich",
        "lokasi": "Switzerland",
        "score_ova": "89.4",
        "teaching": "82.6",
        "rank_teaching": "17",
        "research": "95.4",
        "rank_rsc": "10",
        "citation": "90.7",
        "rank_ctn": "135",
        "income": "59.1",
        "rank_inc": "279",
        "int_outlook": "97.7",
        "rank_int_outlook": "14"
    },
    {
        "id_ova": "13",
        "wrld_rank": "13",
        "nama_univ": "The University of Chicago",
        "lokasi": "United States",
        "score_ova": "88.9",
        "teaching": "86.5",
        "rank_teaching": "13",
        "research": "88.8",
        "rank_rsc": "19",
        "citation": "97.7",
        "rank_ctn": "49",
        "income": "56.2",
        "rank_inc": "303",
        "int_outlook": "74.2",
        "rank_int_outlook": "283"
    },
    {
        "id_ova": "14",
        "wrld_rank": "14",
        "nama_univ": "University of Pennsylvania",
        "lokasi": "United States",
        "score_ova": "88.8",
        "teaching": "86",
        "rank_teaching": "15",
        "research": "88.8",
        "rank_rsc": "20",
        "citation": "97",
        "rank_ctn": "65",
        "income": "75.8",
        "rank_inc": "151",
        "int_outlook": "71.5",
        "rank_int_outlook": "327"
    },
    {
        "id_ova": "15",
        "wrld_rank": "15",
        "nama_univ": "Johns Hopkins University",
        "lokasi": "United States",
        "score_ova": "88.3",
        "teaching": "79.4",
        "rank_teaching": "21",
        "research": "91.5",
        "rank_rsc": "15",
        "citation": "97",
        "rank_ctn": "64",
        "income": "89.5",
        "rank_inc": "73",
        "int_outlook": "75.3",
        "rank_int_outlook": "266"
    },
    {
        "id_ova": "16",
        "wrld_rank": "16",
        "nama_univ": "Tsinghua University",
        "lokasi": "China",
        "score_ova": "88.2",
        "teaching": "90.1",
        "rank_teaching": "9",
        "research": "97.4",
        "rank_rsc": "4",
        "citation": "88",
        "rank_ctn": "182",
        "income": "100",
        "rank_inc": "9",
        "int_outlook": "40.3",
        "rank_int_outlook": "951"
    },
    {
        "id_ova": "17",
        "wrld_rank": "17",
        "nama_univ": "Peking University",
        "lokasi": "China",
        "score_ova": "88.1",
        "teaching": "92.5",
        "rank_teaching": "4",
        "research": "96.7",
        "rank_rsc": "6",
        "citation": "80.4",
        "rank_ctn": "308",
        "income": "91.8",
        "rank_inc": "60",
        "int_outlook": "65",
        "rank_int_outlook": "409"
    },
    {
        "id_ova": "18",
        "wrld_rank": "18",
        "nama_univ": "University of Toronto",
        "lokasi": "Canada",
        "score_ova": "87.4",
        "teaching": "77.3",
        "rank_teaching": "25",
        "research": "93.3",
        "rank_rsc": "12",
        "citation": "92.8",
        "rank_ctn": "113",
        "income": "65.5",
        "rank_inc": "225",
        "int_outlook": "89.7",
        "rank_int_outlook": "115"
    },
    {
        "id_ova": "19",
        "wrld_rank": "19",
        "nama_univ": "National University of Singapore",
        "lokasi": "Singapore",
        "score_ova": "87.1",
        "teaching": "76.4",
        "rank_teaching": "26",
        "research": "93",
        "rank_rsc": "13",
        "citation": "90.2",
        "rank_ctn": "148",
        "income": "87",
        "rank_inc": "86",
        "int_outlook": "94",
        "rank_int_outlook": "63"
    },
    {
        "id_ova": "20",
        "wrld_rank": "20",
        "nama_univ": "Cornell University",
        "lokasi": "United States",
        "score_ova": "85.9",
        "teaching": "80.2",
        "rank_teaching": "20",
        "research": "86.1",
        "rank_rsc": "22",
        "citation": "97.3",
        "rank_ctn": "56",
        "income": "40.4",
        "rank_inc": "905",
        "int_outlook": "76.9",
        "rank_int_outlook": "252"
    },
    {
        "id_ova": "2345",
        "wrld_rank": "Reporter",
        "nama_univ": "Zarqa University",
        "lokasi": "Jordan",
        "score_ova": "n/a",
        "teaching": "n/a",
        "rank_teaching": "0",
        "research": "n/a",
        "rank_rsc": "0",
        "citation": "n/a",
        "rank_ctn": "0",
        "income": "n/a",
        "rank_inc": "0",
        "int_outlook": "n/a",
        "rank_int_outlook": "0"
    }
]